name: 'Upload Action'
description: 'upload file to S3/WebDAV/Hdfs/Ipfs/AliYun OSS/Azure Storage and more'
author: 'Lemon'
inputs:
  provider:
    description: 'The upload provider to use'
    required: true
    default: 'Memory'
  provider_options:
    description: 'Options for the upload provider, formatted as Key=Values per line'
    required: false
    default: ''
  include:
    description: 'The files to include in the upload'
    required: true
    default: '**/*'
  flatten:
    description: 'Flatten the directory structure of the files to upload'
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'upload-cloud'
  color: 'blue'
