name: 'test-webdav'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
    paths-ignore:
      - '**.md'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          provider: webdav
          # bug 1: not support create dir in the root webdav path, not sure is that only occurs in jianguoyun
          provider_options: |
            endpoint=https://dav.jianguoyun.com/dav
            username=${{secrets.webdav_username}}
            password=${{secrets.webdav_password}}
            root=/openDAL/
          include: '__tests__/**'
